config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :hideouts # debug

  # Dashboard Route
  get 'dashboard', to: 'dashboard#index'

  # Route pour Bookings Hideout
  resources :hideouts do
    resources :bookings do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  # Route pour searchbar
  get 'search', to: 'pages#search'
  resources :hideouts # debug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hideout

  validates :date_start, presence: true, comparison: { less_than: :date_end }
  validates :date_end, presence: true, comparison: { greater_than: :date_start }
  validates :status, presence: true
  validates :hideout, presence: true
  validates :user, presence: true


end

app/models/hideout.rb
class Hideout < ApplicationRecord
  include PgSearch::Model

  has_many :bookings
  belongs_to :user
  has_one_attached :cover_picture
  has_many_attached :pictures
  validates :user, presence: true
  validates :address, presence: true, length: { in: 1..150 }, uniqueness: true
  validates :price, presence: true, numericality: true
  validates :overview, presence: true, length: { maximum: 500 }
  validates :title, presence: true, length: { in: 1..30 } # , uniqueness: true /Gaeus : disabled for testing
  validates :cover_picture, presence: true

  # multisearchable against: [:title, :overview]
  pg_search_scope :search_by_title_and_overview,
  against: [ :title, :overview ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  include PgSearch::Model
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hideouts
  has_many :bookings
  has_one_attached :avatar

  validates :nickname, presence: true, length: { maximum: 30 }
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence:true, length: { maximum: 30 }

  multisearchable against: [:nickname, :first_name, :last_name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :avatar, :is_public])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname, :avatar, :is_public])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_hideout, only: [:new, :create]
  before_action :set_booking, only: [:accept, :decline]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.hideout = @hideout
    @booking.user = current_user
    number_of_nights = (@booking.date_end - @booking.date_start).to_i
    @booking. price = number_of_nights * @hideout.price
    @booking.status = "pending"
    if @booking.save
      # redirect_to hideout_path(@hideout)
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking.update(status: "accepted")
    redirect_to dashboard_path(), notice: "Booking accepted!"
  end

  def decline
    @booking.update(status: "declined")
    redirect_to dashboard_path(), alert: "Booking declined!"
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end

  def set_hideout
    @hideout = Hideout.find(params[:hideout_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

end

app/controllers/hideouts_controller.rb
class HideoutsController < ApplicationController

  skip_before_action :authenticate_user!, only: :show

  def show
    @hideout = Hideout.find(params[:id])
    @booking = Booking.new
    @bookings_dates = @hideout.bookings.reject{ |booking| booking.status == "declined"}.map { |booking| [booking.date_start, booking.date_end] }
  end

  def new
    @hideout = Hideout.new

  end

  def create
    @hideout = Hideout.new(hideout_params)
    @hideout.user = current_user
    if @hideout.save
      redirect_to @hideout
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @hideout = Hideout.find(params[:id])
  end

  def update
    @hideout = Hideout.find(params[:id])
    @hideout.update(hideout_params)
    redirect_to hideout_path(@hideout)
  end

  def destroy
    @hideout = Hideout.find(params[:id])
    @hideout.destroy
    redirect_to root_path
  end


  private

  def hideout_params
    params.require(:hideout).permit(:title, :address, :price, :overview, :cover_picture, pictures:[])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home , :search]

  def home
    @hideouts = Hideout.all
  end

  def search
    @hideouts = Hideout.all
    if params[:query].present?
      # ancienne version du code ci dessous, ne fonctionne pas avec plusieurs mots
      # sql_subquery = "title ILIKE :query OR overview ILIKE :query OR address ILIKE :query"
      # @hideouts = @hideouts.where(sql_subquery, query: "%#{params[:query]}%")
      @hideouts = Hideout.search_by_title_and_overview(params[:query])
      # @hideouts = @results.where(searchable_type: "Hideout").map { |searchable| Hideout.find(searchable.searchable_id) }
      # users = @results.where(searchable_type: "User").map { |searchable| User.find(searchable.searchable_id) }
      # users.each do |user|
      #   user.hideouts.each do |hideout|
      #     @hideouts << hideout unless @hideouts.include?(hideout)
      #   end
      # end
    end
    render :home # cette liste pourrait etre supprimée en C/C le contenu de html home dans l'html search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/_user_/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Victor
  </div>
</div>

app/views/_user_/_form_reservation.html.erb
<div data-controller="flatpickr" class="container">
  <div class="row">
    <div class="col">
      <h2>You want to book</h2>
      <%= simple_form_for [hideout, booking] do |f| %>
        <%= f.input :date_start, as: :string,
        input_html: { data: { flatpickr_target: "dateStart" } } %>
        <%= f.input :date_end, as: :string,
        input_html: { data: { flatpickr_target: "dateEnd" } } %>
        <%= f.submit "Réserver" %>
      <% end %>
    </div>
  </div>
</div>

app/views/_user_/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-navbar.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Ajouter un nouveau repère", new_hideout_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%# <%= cl_image_tag current_user.avatar.key, class:"avatar", alt:"dropdown menu" %>
              <%= cl_image_tag(current_user.avatar.key, class:"avatar", alt:"dropdown menu", crop: :thumb, gravity: :face) %>
            <% else %>
              <%= image_tag "user_icon.png", class:"avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Modifier mon compte", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>You want to book</h2>
    <%= simple_form_for [@hideout, @booking] do |f| %>
    <%= f.input :date_start %>
    <%= f.input :date_end %>
    <%= f.submit "Submit Review" %>
    <% end %>


    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div data-controller="dashboard" id="dashboard-container">
  <div id="sidebar">
    <h2>Ma Dashboard</h2>
    <ul>
      <li><button id="show-hideouts" data-action="dashboard#showHideouts">Mes Repères</button></li>
      <li><button id="show-reservations" data-action="dashboard#showReservations">Gerer mes demandes de Repères</button></li>
      <li><button id="show-rents" data-action="dashboard#showRents">Mes réservations de Repères</button></li>
      <li><%= link_to "Modifier mon compte", edit_user_registration_path %></li>
      <li><%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete} %></li>
    </ul>
  </div>

  <div id="dashboard-display">

    <div class="container" id="user-hideouts"  data-dashboard-target="hideouts" style="">
      <div>
        <div>
          <h2>Vos repères:</h2>
          <ul>
            <% current_user.hideouts.each do |hideout| %>
              <div>

                <% if hideout.cover_picture.attached? %>
                  <%= cl_image_tag hideout.cover_picture.key, class: "img-dash"%>
                <% else %>
                <img src="https://media.istockphoto.com/id/1629004972/fr/vectoriel/casque-et-%C3%A9quipement-s%C3%A9curit%C3%A9-et-protection-ing%C3%A9nieur-symboles-de-construction-de-travail.jpg?s=612x612&w=0&k=20&c=Ysj5EhRTeeC9oZ16IejpmWiNX0Jwx_oOd6FuSDQb-OQ=" alt="Work in progess">
                <% end %>
                <li><%= hideout.title %></li>
                <li><%= hideout.overview %></li>
                <li><%= hideout.price %></li>
                <%= link_to "Modifier", edit_hideout_path(hideout), class: "btn btn-primary" %>
                <% confirm = hideout.bookings  ? "La demande échouera s'il y a des réservations en cours"  : "confirmer la suppression?" %>
                <%= link_to "Supprimer", hideout_path(hideout) ,data: {turbo_confirm: confirm, turbo_method: :delete}, class: "btn btn-danger" %>
              </div>
              <br>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container" id="user-reservations" data-dashboard-target="reservations" style="display: none" >
      <div>
        <div>
          <h2>Vos locations:</h2>
          <ul>
            <% current_user.hideouts.each do |hideout| %>
              <% hideout.bookings.each do |booking| %>
                <div>
                  <h4><%= hideout.title %></h4>
                  <li>Démarre le: <%= booking.date_start %></li>
                  <li>Se termine le: <%= booking.date_end %></li>
                  <li>Status: <%= booking.status.capitalize %></li>
                  <li>Prix: <%= booking.price %>€</li>
                  <% if booking.status == "pending" %>
                  <%= link_to "Approuver", accept_hideout_booking_path(hideout_id: hideout.id, id: booking.id), data: {turbo_method: :patch} , class: "btn btn-success" %>
                  <%= link_to "Rejeter", decline_hideout_booking_path(hideout_id: hideout.id, id: booking.id), data: {turbo_method: :patch}, class: "btn btn-danger" %>
                  <% end %>
                </div>
                <br>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container" id="user-rents" data-dashboard-target="rents" style="display: none">
      <div>
        <div>
          <h2>Vos réservations:</h2>
          <ul>
            <% current_user.bookings.each do |booking| %>
              <div>
                <h4><%= booking.hideout.title %></h4>
                <li>Démarre le: <%= booking.date_start %></li>
                <li>Se termine le: <%= booking.date_end %></li>
                <li>Status: <%= booking.status.capitalize %></li>
                <li>Prix: <%= booking.price %>€</li>
              </div>
              <br>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hideouts/edit.html.erb
<div class="container-local center-form-hideout">
    <div class="container-edit-hideout-form">
        <%= simple_form_for @hideout do |f| %>
          <%= f.input :title,
                      required: true,
                      autofocus: true,
                      label: "Titre",
                      input_html: { autocomplete: "title" } %>
          <%= f.input :address,
                      required: true,
                      label: "Adresse",
                      input_html: { autocomplete: "address" } %>
          <%= f.input :overview,
                      required: true,
                      label: "Description",
                      input_html: { autocomplete: "overview" } %>
          <%= f.input :price,
                      required: true,
                      label: "Prix",
                      input_html: { autocomplete: "price" } %>
          <%= f.input :cover_picture, as: :file,
                      label: "Photo de présentation",
                      required: true %>
          <%= f.input :pictures, as: :file, label: "Photo de description", input_html: { multiple: true },
                      required: false %>
          <%= f.button :submit, value:"Mettre à jour", class:"btn btn-primary"%>
        <% end %>
    </div>
</div>

app/views/hideouts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <%= simple_form_for @hideout do |f| %>
      <%= f.error_notification %>
      <%= f.input :title,
                  label: "Titre",
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "Titre" } %>
      <%= f.input :address,
                  label: "Adresse",
                  required: true,
                  input_html: { autocomplete: "Adresse" } %>
      <%= f.input :overview,
                  label: "Déscription",
                  required: true,
                  input_html: { autocomplete: "Description" } %>
      <%= f.input :price,
                  label: "Prix",
                  required: true,
                  input_html: { autocomplete: "Prix" } %>
      <%= f.input :cover_picture, as: :file,
                  label: "Photo de présentation",
                  required: true %>
      <%= f.input :pictures, as: :file,
                  label: "Photos de description",
                  input_html: { multiple: true },
                  required: false %>
      <%= f.button :submit, class: "btn btn-primary", value: "Enregistrer" %>
      <% end %>
    </div>
  </div>
</div>

app/views/hideouts/show.html.erb
<div class="container-local">
  <div class="info-owner">
    <div class="info-owner-avatar">
      <% if @hideout.user.avatar.attached? %>
        <%= cl_image_tag @hideout.user.avatar.key, class:"avatar-large avatar-border", alt:"avatar" %>
      <% else %>
        <%= image_tag "user_icon.png", class:"avatar-large avatar-border", alt: "avatar" %>
      <% end %>
    </div>
    <p>Pour plus d'informations, vous pouvez contactez <strong><%=@hideout.user.nickname.capitalize %></strong> : <a href="mailto:<%=@hideout.user.email%>"><i><%=@hideout.user.email %></i></a></p>
  </div>
  <div class="show-hideout">
    <div class="show-hideout-image">
      <% if @hideout.pictures.attached? %>
        <div id="carouselExample" class="carousel slide carousel-radius w-100">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= cl_image_tag @hideout.cover_picture.key, alt:"Cover picture" %>
            </div>
            <% @hideout.pictures.each do |picture| %>
              <div class="carousel-item">
                <%= cl_image_tag picture.key, alt:"Pictures" %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <% elsif @hideout.cover_picture.attached?%>
          <div>
            <%= cl_image_tag @hideout.cover_picture.key%>
          </div>
        <% else %>
            <img src="https://media.istockphoto.com/id/1629004972/fr/vectoriel/casque-et-%C3%A9quipement-s%C3%A9curit%C3%A9-et-protection-ing%C3%A9nieur-symboles-de-construction-de-travail.jpg?s=612x612&w=0&k=20&c=Ysj5EhRTeeC9oZ16IejpmWiNX0Jwx_oOd6FuSDQb-OQ=" alt="Work in progess">
      <% end %>
    </div>
    <div class=show-hideout-content>
      <div>
        <h2><%= @hideout.title %></h2>
        <p><%= @hideout.address %></p>
        <p><%= @hideout.overview %></p>
        <p class=""><%= @hideout.price %> €</p>
        <% if current_user != @hideout.user %>
          <div data-controller="toggle">
            <button data-action="click->toggle#fire" class="btn btn-outline-primary">Reserver</button>
            <div data-toggle-target="togglableElement" class="d-none">
              <%= render "shared/form_reservation", booking: @booking, hideout: @hideout %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lairs & Lodges</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hind+Vadodara:wght@300;400;500;600;700&family=Homenaje&family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="background-body">
    <div class="wrapper">
      <%= render "shared/navbar" %>
      <p style="height: 0; padding:0; margin: 0;" class="notice"><%= notice %></p>
      <p style="height: 0; padding:0; margin: 0;" class="alert"><%= alert %></p>
      <main class="content">
        <%= yield %>
      </main>
        <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-local">
      <!-- début de la barre de recherche-->
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: search_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Rechercher un repère..."
            %>
          <%= submit_tag "rechercher", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

      <!-- fin de la barre de recherche-->
<div class="cards-hideouts">
    <% @hideouts.each do |hideout| %>
      <%= link_to hideout_path(hideout), class: 'link_to' do %>
      <div class="card-hideout">
        <div class="card-img">

          <% if hideout.cover_picture.attached? %>
            <%= cl_image_tag hideout.cover_picture.key%>
          <% else %>
          <img src="https://media.istockphoto.com/id/1629004972/fr/vectoriel/casque-et-%C3%A9quipement-s%C3%A9curit%C3%A9-et-protection-ing%C3%A9nieur-symboles-de-construction-de-travail.jpg?s=612x612&w=0&k=20&c=Ysj5EhRTeeC9oZ16IejpmWiNX0Jwx_oOd6FuSDQb-OQ=" alt="Work in progess">
          <% end %>

        </div>
        <div class="card-body">
          <div class="overflow-body-h2 text">
            <h2><%= hideout.title.split(";").first %></h2>
          </div>
          <div>
            <div class="price-card">
                <p><%= hideout.price %>€</p>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
<%# page inutilisée par le code, car redirigée dans la route, cette page n'est pas nécessaire et peux être supprimée %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container-local footer-local">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with no <i class="fas fa-heart"></i>
    </div>
  </div>
</div>

app/views/shared/_form_reservation.html.erb
<div data-controller="flatpickr" class="container">
  <div class="row">
    <div class="col">

      <h2 class="margin-reservation-h2">You want to book</h2>
      <%= simple_form_for [hideout, booking] do |f| %>
        <%= f.input :date_start, as: :string,
        input_html: { data: { flatpickr_target: "dateStart" } } %>
        <%= f.input :date_end, as: :string,
        input_html: { data: { flatpickr_target: "dateEnd" } } %>
        <%= f.submit "Réserver" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_manage_hideouts.html.erb
<h2>Gérer mes planques, bases et repères :</h2>
  <ul>
    <% current_user.hideouts.each do |hideout| %>
      <div>

        <% if hideout.cover_picture.attached? %>
          <%= cl_image_tag hideout.cover_picture.key%>
        <% else %>
        <img src="https://media.istockphoto.com/id/1629004972/fr/vectoriel/casque-et-%C3%A9quipement-s%C3%A9curit%C3%A9-et-protection-ing%C3%A9nieur-symboles-de-construction-de-travail.jpg?s=612x612&w=0&k=20&c=Ysj5EhRTeeC9oZ16IejpmWiNX0Jwx_oOd6FuSDQb-OQ=" alt="Work in progess">
        <% end %>
        <li><%= hideout.title %></li>
        <li><%= hideout.overview %></li>
        <li><%= hideout.price %></li>
        <%= link_to "Modifier", edit_hideout_path(hideout), class: "btn btn-primary" %>
        <% confirm = hideout.bookings  ? "Vous ne devriez pas supprimer une propriété tant qu'il y a des réservations sur elle"  : "etes vous sur??" %>
        <%= link_to "Supprimer", hideout_path(hideout) ,data: {turbo_confirm: confirm, turbo_method: :delete}, class: "btn btn-danger" %>
      </div>
      <br>
    <% end %>
  </ul>

app/views/shared/_manage_rents.html.erb
<h2>Your Reservations are:</h2>
<ul>
  <% current_user.bookings.each do |booking| %>
    <div>
      <h4><%= booking.hideout.title %></h4>
      <li>Start Date: <%= booking.date_start %></li>
      <li>End Date: <%= booking.date_end %></li>
      <li>Status: <%= booking.status.capitalize %></li>
      <li>Price: <%= booking.price %>€</li>
    </div>
    <br>
  <% end %>
</ul>

app/views/shared/_manage_reservations.html.erb
<h2>Mes biens en location :</h2>
<ul>
  <% current_user.hideouts.each do |hideout| %>
    <% hideout.bookings.each do |booking| %>
      <div>
        <li>Commence: <%= booking.date_start %></li>
        <li>Se termine: <%= booking.date_end %></li>
        <li>Status: <%= booking.status.capitalize %></li>
        <li>Prix: <%= booking.price %>€</li>

        <% if booking.status == "pending" %>
        <%= link_to "Accept", accept_hideout_booking_path(hideout_id: hideout.id, id: booking.id), data: {turbo_method: :patch} , class: "btn btn-success" %>
        <%= link_to "Decline", decline_hideout_booking_path(hideout_id: hideout.id, id: booking.id), data: {turbo_method: :patch}, class: "btn btn-danger" %>
        <% end %>
      </div>
      <br>
    <% end %>
  <% end %>
</ul>